### ISSUE TITLE
criu-1.4, criu-1.5 fail to build with protobuf-c-1.1.0, but not 1.0.2

### ISSUE THREAD

**Issue by dlan17** [protobuf-c/protobuf-c#185]
Hi， as the title says, we‘ve got build error when try to build criu-1.4/1.5 with protobuf-c-1.1.0, but no problem with 1.0.2
any idea what's the problem?
also see down stream bug:  https://bugs.gentoo.org/show_bug.cgi?id=542858

x86_64-pc-linux-gnu-gcc -c -O2 -pipe -march=core2   -Wall -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -Iprotobuf/ protobuf/core-x86.pb-c.c -o protobuf/core-x86.o
x86_64-pc-linux-gnu-gcc -c -O2 -pipe -march=core2   -Wall -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -Iprotobuf/ protobuf/core.pb-c.c -o protobuf/core.o
x86_64-pc-linux-gnu-gcc -c -O2 -pipe -march=core2   -Wall -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -Iprotobuf/ protobuf/core-aarch64.pb-c.c -o protobuf/core-aarch64.o
In file included from protobuf/opts.pb-c.h:17:0,
                 from protobuf/core-x86.pb-c.h:17,
                 from protobuf/core-x86.pb-c.c:9:
protobuf/google/protobuf/descriptor.pb-c.h:812:8: warning: "/*" within comment [-Wcomment]
    *   /* Block comment attached
 ^
protobuf/google/protobuf/descriptor.pb-c.h:815:4: error: expected specifier-qualifier-list before ‘*’ token
    *   /* Block comment attached to
    ^
In file included from protobuf/opts.pb-c.h:17:0,
                 from protobuf/core-x86.pb-c.h:17,
                 from protobuf/core.pb-c.h:17,
                 from protobuf/core.pb-c.c:9:
protobuf/google/protobuf/descriptor.pb-c.h:812:8: warning: "/*" within comment [-Wcomment]
    *   /* Block comment attached
 ^
protobuf/google/protobuf/descriptor.pb-c.h:815:4: error: expected specifier-qualifier-list before ‘*’ token
    *   /* Block comment attached to
    ^
protobuf/Makefile:93: recipe for target 'protobuf/core-x86.o' failed
make[1]: *** [protobuf/core-x86.o] Error 1
make[1]: *** Waiting for unfinished jobs....
protobuf/Makefile:93: recipe for target 'protobuf/core.o' failed
make[1]: *** [protobuf/core.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/sys-process/criu-1.5-r1/work/criu-1.5'
Makefile:155: recipe for target 'protobuf' failed
make: *** [protobuf] Error 2
make: *** Waiting for unfinished jobs....
 * ERROR: sys-process/criu-1.5-r1::gentoo failed (compile phase):
 *   emake failed
 *

**Comment by edmonds** [comment]
Hi,

This was introduced by the copying of `.proto` comments into the generated header files in #175, which was released in 1.1.0. There is a fix in #180 which will be in 1.1.1.

I'll see about pushing out a 1.1.1 release ASAP, thanks for the report!

**Comment by edmonds** [comment]
Fixed in the 1.1.1 release.
