### ISSUE TITLE
./protoc-c/c_helpers.h:179:46: error: ‘class google::protobuf::FileDescriptorLegacy’ has no member named ‘syntax’

### ISSUE THREAD

**Issue by neel-patel-1** [protobuf-c/protobuf-c#730]
Hello,

When running:
./autogen.sh && ./configure && make

I get this error (currently on v1.5.0: commit 8c201f6e47a53feaab773922a743091eb6c8972a):
```
In file included from protoc-c/c_primitive_field.cc:64:                                                                                                                                                                                                  
./protoc-c/c_helpers.h: In function ‘int google::protobuf::compiler::c::FieldSyntax(const google::protobuf::FieldDescriptor*)’:                                                                                                                          
./protoc-c/c_helpers.h:179:46: error: ‘class google::protobuf::FileDescriptorLegacy’ has no member named ‘syntax’                                                                                                                                        
  179 |   return FileDescriptorLegacy(field->file()).syntax() == FileDescriptorLegacy::SYNTAX_PROTO3 ? 3 : 2;
```

**Comment by uablrek** [comment]
I get the same. Protobuf version `protobuf-27.2`

**Comment by uablrek** [comment]
But it compiles with `protobuf-25.4` @neel-patel-1

**Comment by jflopezfdez** [comment]
@lantian-lan-tian's suggestion worked perfectly for me, although I went about patching the source code a little differently. I basically wasn't super sure where the project root is exactly (meaning, is it the root of the vcpkg directory, the root of the portfiles directory, is it my project directory?), so this is what I did:

I first ran this command:

```bash
$ vcpkg edit protobuf-c
```

This gets you an editor opened right up to the `portfile.cmake` file. Then, you just need to add the new patch to the `vcpkg_from_github` command directive, right after the two previous ones, like this:

```cmake
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO protobuf-c/protobuf-c
    REF v${VERSION}
    SHA512 4c540ca58b65e59aaf7149124d915f106e91fc79d60c6ef80b62faf288843250375e13f8773fd24f2ff27485dc2d2e597f0a95e39c186a30069eb470abd28ae7
    HEAD_REF master
    PATCHES
        fix-crt-linkage.patch
        fix-dependency-protobuf.patch
        protobuf-26.patch
)
```

At this point, you should be good to go. The installation should succeed now.

```bash
$ vcpkg install --overlay-triplets=x64-windows,x64-windows-static protobuf-c[tools] grpc[codegen]
```

This is just an example command, you can install `protobuf-c` however you normally do it.

---

I might have missed a step, so let me know if you run into any problems :) Thanks again, @lantian-lan-tian!

**Comment by edmonds** [comment]
This is #711 which will be released in protobuf-c 1.5.1. protobuf 26.0 and newer have changes that broke protobuf-c 1.5.0 and previous releases.
